# The Docker image that will be used to build your app
image: python:3.11
# Functions that should be executed before the build script is run
before_script:
  - python -m venv .venv
  - python -m pip install --upgrade pip
  - python -m pip install -e .[docs]
pages:
  script:
    - make -C docs html
    - cp -r docs/_build/html public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
